#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           10
bspc config border_width         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# -- other stuff --

# no rounded corners on monocle
sh ~/scripts/no-rounded-monocle.sh &
# no beep
xset -b &

# -- autostart --

sh ~/.config/picom/launch.sh &
sh ~/.config/polybar/launch.sh &
sh ~/.config/mopidy/launch.sh &
sh ~/scripts/bg-lock.sh &
fcitx5 -d -r &
batsignal -W "low battery" -C "critically low battery" -D "dangerously low battery" -I battery -b

