#!/bin/bash

#		--match-text "Stopped" "\"echo ' '\"" \
#		--match-text "No player could handle this command" "\"echo ' '\"" \
#		--match-text "No players found" "--before-text ' ' \"echo ' '\"" \
#		--before-text 'ﱘ ' \

zscroll --scroll-padding " ~ " \
		--delay 0.5 \
		--length 35 \
		--match-command "echo $(playerctl -s status) $(playerctl -s metadata artist)" \
		--match-text "Paused" "--scroll false" \
		--update-interval 2 \
		--update-check true "playerctl -s metadata --format '{{lc(artist)}} ~ {{lc(title)}}'" &

wait
